---
driver:
  # using docker to test
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
<<<<<<< HEAD
  #group_vars_path: group_vars/all/main.yml
=======
>>>>>>> f84436d23e0b436775540f69aa3203d07c268c96
  # list of ansible galaxy requirements from the roles meta/main.yml
  #requirements_path: dependencies.yml

platforms:
  - name: centos-6.8

<<<<<<< HEAD

suites:
  # suites found at /test/integration/$test-name
  - name: generic

  - name: mariadb
    driver_config:
      forward:
      - 3306:3306

  - name: nginx
    driver_config:
      forward:
      - 80:80


  - name: tomcat
    driver_config:
      forward:
      - 8080:8080
=======
suites:
  # suites found at /test/integration/$test-name
  - name: default
  - name: generic
>>>>>>> f84436d23e0b436775540f69aa3203d07c268c96
